# Generated by Django 5.1.4 on 2026-02-19 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsultingInquiry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(max_length=200)),
                ("contact_title", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company_website", models.URLField(blank=True)),
                ("industry", models.CharField(max_length=100)),
                ("company_size", models.CharField(blank=True, max_length=50)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("agentic_ai", "Agentic AI Systems"),
                            ("generative_ai", "Generative AI Solutions"),
                            ("autonomous_systems", "Autonomous Systems"),
                            ("multi_agent", "Multi-Agent Systems"),
                            ("ai_transformation", "AI Transformation"),
                            ("ai_migration", "AI Migration"),
                            ("ai_modernization", "AI Modernization"),
                            ("devsecops", "DevSecOps"),
                            ("cybersecurity", "Cybersecurity & Compliance"),
                            ("cloud_architecture", "Cloud Architecture"),
                            ("kubernetes", "Kubernetes/OpenShift"),
                            ("mlops", "MLOps"),
                            ("data_engineering", "Data Engineering"),
                            ("ai_research", "AI Research & Innovation"),
                            ("ai_governance", "AI Governance & Ethics"),
                            ("training", "Training & Education"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("project_title", models.CharField(max_length=300)),
                ("project_description", models.TextField()),
                ("business_objectives", models.TextField(blank=True)),
                ("current_technology_stack", models.TextField(blank=True)),
                ("timeline", models.CharField(blank=True, max_length=200)),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_50k", "Under $50,000"),
                            ("50k_100k", "$50,000 - $100,000"),
                            ("100k_250k", "$100,000 - $250,000"),
                            ("250k_500k", "$250,000 - $500,000"),
                            ("500k_1m", "$500,000 - $1,000,000"),
                            ("over_1m", "Over $1,000,000"),
                            ("tbd", "To Be Determined"),
                        ],
                        default="tbd",
                        max_length=20,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("low", "Exploratory - No Rush"),
                            ("medium", "Planning Phase"),
                            ("high", "Active Project - Need Soon"),
                            ("critical", "Urgent - Immediate Need"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("how_did_you_hear", models.CharField(blank=True, max_length=200)),
                ("additional_notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualifying", "Qualifying"),
                            ("proposal", "Proposal Sent"),
                            ("negotiation", "In Negotiation"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("on_hold", "On Hold"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("internal_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Consulting inquiries",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultingEngagement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("discovery", "Discovery"),
                            ("assessment", "Assessment"),
                            ("design", "Design & Architecture"),
                            ("development", "Development"),
                            ("testing", "Testing & Validation"),
                            ("deployment", "Deployment"),
                            ("maintenance", "Maintenance & Support"),
                            ("completed", "Completed"),
                        ],
                        default="discovery",
                        max_length=20,
                    ),
                ),
                ("deliverables", models.JSONField(default=list)),
                ("technologies", models.JSONField(default=list)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_end_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "inquiry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="engagements",
                        to="consulting.consultinginquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
