# Generated by Django 5.2.11 on 2026-02-23 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consulting", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultinginquiry",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("agentic_ai", "Agentic AI Systems"),
                    ("generative_ai", "Generative AI Solutions"),
                    ("autonomous_systems", "Autonomous Systems"),
                    ("multi_agent", "Multi-Agent Systems"),
                    ("ai_transformation", "AI Transformation"),
                    ("ai_migration", "AI Migration"),
                    ("ai_modernization", "AI Modernization"),
                    ("devsecops", "DevSecOps"),
                    ("cybersecurity", "Cybersecurity & Compliance"),
                    ("cloud_architecture", "Cloud Architecture"),
                    ("kubernetes", "Kubernetes/OpenShift"),
                    ("mlops", "MLOps"),
                    ("data_engineering", "Data Engineering & Data Science"),
                    ("iot_integration", "IoT Device Integration"),
                    ("ai_research", "AI Research & Innovation"),
                    ("ai_governance", "AI Governance & Ethics"),
                    ("training", "Training & Education"),
                    ("other", "Other"),
                ],
                max_length=30,
            ),
        ),
    ]
